### PR TITLE
add parameter for outlier detection algorithm

### PR DESCRIPTION
**Pull request by jachymsol**

### CODE REVIEW

**Comment by jancervenka** [comment]
function `[to_experiment](https://github.com/avast/ep-stats/blob/master/src/epstats/server/req.py#L325)` needs to use the new argument as well

```python
    def to_experiment(self, statsd: StatsClient):
        metrics = [m.to_metric() for m in self.metrics]
        checks = [c.to_check() for c in self.checks]
        return EvExperiment(
            self.id,
            self.control_variant,
            metrics,
            checks,
            date_from=self.date_from,
            date_to=self.date_to,
            date_for=self.date_for,
            unit_type=self.unit_type,
            variants=self.variants,
            statsd=statsd,
            filters=[f.to_filter() for f in self.filters] if self.filters else [],
            outlier_detection_algorithm=self.outlier_detection_algorithm
        )
```

Also, I would add a unit test to [tests/epstats/server/test_req.py](https://github.com/avast/ep-stats/blob/master/tests/epstats/server/test_req.py ) to make sure it works

**Review by jancervenka — CHANGES_REQUESTED** [review]
function [to_experiment](https://github.com/avast/ep-stats/blob/master/src/epstats/server/req.py#L325) needs to use the new argument as well

```python
    def to_experiment(self, statsd: StatsClient):
        metrics = [m.to_metric() for m in self.metrics]
        checks = [c.to_check() for c in self.checks]
        return EvExperiment(
            self.id,
            self.control_variant,
            metrics,
            checks,
            date_from=self.date_from,
            date_to=self.date_to,
            date_for=self.date_for,
            unit_type=self.unit_type,
            variants=self.variants,
            statsd=statsd,
            filters=[f.to_filter() for f in self.filters] if self.filters else [],
            outlier_detection_algorithm=self.outlier_detection_algorithm
        )
```

Also, I would add a unit test to [tests/epstats/server/test_req.py](https://github.com/avast/ep-stats/blob/master/tests/epstats/server/test_req.py ) to make sure it works

**Comment by jachymsol** [comment]
Since this parameter does not have any validation checks (similar to `filters`) we decided that unit tests are not needed

**Review by jancervenka — APPROVED** [review]
lgtm 👍

**Pull request merged**
